<?php
function get_strike ($language) {
  if ($language=="no") {
    $bodyline = "<h3>VIKTIG MELDING TIL REISENDE</h3><b style='color: #aa0000'>Sikkerhetskontroll&oslash;rer tilknyttet Norsk Arbeidsmandsforbund ved noen av <a href='http://www.avinor.no/'>Avinor</a>s lufthavner er tatt ut i streik med virkning fra kl. 20:00 i dag, fredag 01. juni. Dette f&aring;r konsekvenser for avviklingen av flytrafikken.<br /><br />Streiken rammer sikkerhetskontrollene ved flyplassene i Stavanger, Bergen, Trondheim og Troms&oslash; i tillegg til Oslo lufthavn, Gardermoen.<br /><br />Kapasiteten i sikkerhetskontrollen ved Oslo lufthavn Gardermoen blir halvert. Det oppfordres til at passasjerer som ikke m&aring; reise i helgen kansellerer eller booker om flyreisen til en senere avgang. Flere flyselskap tilbyr &aring; endre billetten kostnadsfritt. Passasjerer som likevel velger &aring; fly, m&aring; m&oslash;te i god tid og forholde seg til informasjon fra flyselskapene i forhold til den enkelte flyvning.<br /><br />
Ved samtlige av de lufthavnene der innleide sikkerhetskontroll&oslash;rer er i streik fra kl. 20:00 i kveld blir det redusert kapasitet i sikkerhetsslusene - og k&oslash; m&aring; forventes.<br /><br /><a href='http://www.avinor.no/'>Les mer hos Avinor p&aring; www.avinor.no</a></b>";
  }
  if ($language=="en") {
    $bodyline = "<h3>IMPORTANT NOTICE TO TRAVELLERS</h3><b style='color: #aa0000'>Security controllers at some of <a href='http://www.avinor.no/'>Avinor</a>'s airports, who are members of the union Norsk Arbeidsmandsforbund, have been brought out on strike with effect from 20.00 today, Friday 1 June. This will have consequences for air traffic.<br /><br />The strike will affect the security checkpoints at the airports in Stavanger, Bergen, Trondheim and Troms&oslash;, as well as Oslo Airport Gardermoen.<br /><br />Capacity at the security checkpoints at Oslo Airport Gardermoen will be halved. Passengers who do not urgently need to travel this weekend are advised to cancel their flights or rebook for a later departure. Several airlines are offering to change tickets without charge. Passengers who still choose to fly must allow plenty of time and refer to information from the airlines about individual flights.<br /><br />At all of the airports where contracted security controllers are on strike from 20.00 this evening, capacity at the security checkpoints will be reduced - and queues must be expected.</b><br /><br /><a href='http://www.avinor.no/en/avinor'>Read more at Avinor on www.avinor.no</a>";
  }
  return $bodyline;
}
?>
